<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="0.023">
  <testcase classname="__main__.qa_multiply_py_ff" name="test_001_t" time="0.0231">
    <failure type="exceptions.AssertionError">1 != 2.0 within 6 places
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "qa_multiply_py_ff.py", line 48, in test_001_t
    self.assertFloatTuplesAlmostEqual(expected_result, result_data, 6)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr_unittest.py", line 90, in assertFloatTuplesAlmostEqual
    self.assertAlmostEqual (a[i], b[i], places, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 561, in assertAlmostEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
